name: incipere
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.8.1 # ou a versão mais recente
  provider: ^6.0.5 # Gerenciamento de estado
  flutter_dotenv: ^5.0.2 # Para gerenciar variáveis de ambiente
  http: ^1.2.2 # Para chamadas HTTP adicionais
  shared_preferences: ^2.2.0 # Para armazenamento local
  flutter_secure_storage: ^9.2.2 # Para armazenar dados sensíveis
  cached_network_image: ^3.2.0 # Para exibir imagens com cache
  intl: ^0.20.0 # Para formatação de datas
  url_launcher: ^6.1.8 # Para abrir links externos
  flutter_native_splash: ^2.3.2 # Para personalizar o splash screen
  logger: ^2.5.0
  image_picker: ^1.1.2
  universal_io: ^2.2.2
  image_picker_for_web: ^3.0.6
  flutter_colorpicker: ^1.1.0
  file_picker: ^8.1.4
  uuid: ^4.5.1
  timeago: ^3.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

